### PR TITLE
UP-239: proposed an update of the `Running the example` documentation

### PR DESCRIPTION
**Pull request by cvandrei**
Maybe it's just me being completely new to Python but the following changes might have saved me some time.

Feel free to accept the pull request if this opinion is being shared...or otherwise ignore it.

### CODE REVIEW

**Comment by thinkberg** [comment]
using pip3 or python3 within the venv should not be necessary, can you check that please and possible change the PR, please.

**Comment by thinkberg** [comment]
UP-42, UP-240, UP-241, UP242

**Comment by cvandrei** [comment]
As we just discussed I wanted to try:

```
python3 -m venv venv3
. venv3/bin/activate
pip install -r requirements.txt
python3 examples/test-protocol.py
```

This failed in the `pip install -r requirements.txt` step with the following error:

```
Building wheels for collected packages: ed25519, twofish
  Running setup.py bdist_wheel for ed25519 ... error
  Complete output from command /home/cvandrei/git/ubirch/ubirch-protocol-python/venv3/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7wb0vwwj/ed25519/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmp5yhtj336pip-wheel- --python-tag cp35:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for ed25519
  Running setup.py clean for ed25519
  Running setup.py bdist_wheel for twofish ... error
  Complete output from command /home/cvandrei/git/ubirch/ubirch-protocol-python/venv3/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7wb0vwwj/twofish/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpwetha717pip-wheel- --python-tag cp35:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for twofish
  Running setup.py clean for twofish
Failed to build ed25519 twofish
Installing collected packages: msgpack, ed25519, twofish, pyasn1, pyasn1-modules, pycryptodome, javaobj-py3, pyjks, certifi, idna, urllib3, chardet, requests, six, requests-mock
  Running setup.py install for ed25519 ... done
  Running setup.py install for twofish ... done
Successfully installed certifi-2018.8.24 chardet-3.0.4 ed25519-1.4 idna-2.7 javaobj-py3-0.2.4 msgpack-0.5.6 pyasn1-0.4.4 pyasn1-modules-0.2.2 pycryptodome-3.6.6 pyjks-18.0.0 requests-2.19.1 requests-mock-1.5.2 six-1.11.0 twofish-0.3.0 urllib3-1.23
```

If I run `python3 examples/test-protocol.py` afterwards I'm back to square one with the script unable to resolve the ubirch package:

```
Traceback (most recent call last):
  File "examples/test-protocol.py", line 30, in <module>
    import ubirch
ImportError: No module named 'ubirch'
```

**Comment by cvandrei** [comment]
The following sequence works though:

```
pip3 install -r requirements.txt
pip3 install ubirch-protocol
python3 examples/test-protocol.py
# changing env to `dev` in `demo-device.ini and rerunning `examples/test-protocol.py`
```

**Comment by cvandrei** [comment]
What also works despite errors in two of the steps:

```
python3 -m venv venv3
. venv3/bin/activate
pip install -r requirements.txt # produces wheel related errors
pip install ubirch-protocol # produces wheel related error
python3 examples/test-protocol.py
```

**Pull request merged**
